CLASS zbp_r_pmtadvheader DEFINITION
PUBLIC
    ABSTRACT
    FINAL
    FOR BEHAVIOR OF zr_pmtadvheader.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_R_PMTADVHEADER IMPLEMENTATION.
ENDCLASS.
